export type Language = 'english' | 'türkçe';

// ─── English ─────────────────────────────────────────────────────────────────

const english3: string[] = [
  "the","and","for","are","but","not","you","all","any","can","had","her","was",
  "one","our","out","day","get","has","him","his","how","new","now","old","see",
  "two","way","who","eye","act","add","age","air","arm","art","ask","bad","bag",
  "bar","bed","bet","big","bit","box","boy","bus","car","cat","cup","cut","dad",
  "dog","dry","due","ear","eat","egg","end","far","fat","few","fit","fly","fun",
  "gas","gun","guy","hit","hot","ice","job","joy","key","kid","lay","leg","let",
  "lie","lip","low","map","mom","mud","net","odd","oil","pay","pen","pet","pie",
  "pin","pop","put","red","rub","run","sad","sea","set","shy","sin","sit","six",
  "ski","sky","son","sun","tax","tea","ten","tip","toe","top","try","use","war",
  "win","yes","yet","zoo","ado","ago","aid","aim","ale","ape","apt","arc","awe",
  "axe","bay","bee","bin","bog","bow","bye","cab","cob","cod","cog","cop","cow",
  "cry","dab","dam","den","dew","dim","din","dip","doe","dug","dun","dye","elf",
  "elm","emu","era","eve","ewe","fad","fan","fee","fen","fir","foe","fog","fox",
  "fry","gag","gap","gel","gem","gin","gnu","gob","gum","gut","gym","ham","hew",
  "hog","hop","hub","hug","hum","hut","imp","inn","ion","ivy","jab","jag","jam",
  "jar","jaw","jay","jet","jig","jot","jug","keg","lab","lad","lap","law","lax",
  "lea","led","lid","lit","log","lot","lug","lux","mad","man","mar","mat","mob",
  "mop","mow","nab","nag","nap","nip","nod","nun","oar","ode","orb","ore","owl",
  "own","pan","pat","paw","pea","peg","pit","ply","pod","pox","pro","pub","pug",
  "pun","pup","pry","ram","raw","ray","rib","rid","rig","rim","rot","row","sac",
  "sag","sap","saw","say","sew","sip","sir","sob","sod","sow","spa","sty","sue",
  "sum","tab","tan","tar","tap","tub","tug","van","vat","via","vim","vow","wag",
  "wan","wax","web","wed","wit","woe","wok","woo","yam","yap","yew","yip","yam",
  "ace","ash","ave","awl","aye","bit","boo","bop","bub","bud","bug","bun","dew",
  "duo","err","fax","fix","fiz","fly","fur","gag","gal","gig","goo","grr","gut",
  "hag","hap","hay","hem","hen","hex","hey","hew","hub","huh","jab","knob","koi",
  "lob","lop","lox","mob","nix","ooh","pat","pun","pew","rah","rap","rev","rex",
  "rum","rut","rye","sax","she","sis","ski","sky","sly","spy","sub","syn","tab",
  "tad","tat","tie","tin","tip","ton","tow","toy","tug","ugh","urn","vim","vow",
  "wag","wick","wig","wiry","wit","wiz","yak","yen","yore","zen","zip","zit","zap",
];

const english4: string[] = [
  "book","game","life","time","year","work","code","play","fast","slow","good",
  "last","long","make","many","more","most","only","over","very","word","love",
  "help","find","look","hand","part","able","area","army","away","baby","back",
  "ball","band","bank","base","bath","bear","beat","beer","bell","belt","best",
  "bill","bird","blow","blue","boat","body","bomb","bond","bone","born","both",
  "bowl","burn","bush","busy","cake","call","calm","came","camp","card","care",
  "case","cash","cast","cell","chat","chip","city","club","coal","coat","cold",
  "come","cook","cool","copy","core","cost","crew","crop","dark","data","date",
  "dawn","dead","deal","dear","debt","deep","deny","desk","diet","dirt","dish",
  "disk","does","done","door","dose","down","draw","drop","drug","dual","duke",
  "dust","duty","each","earn","ease","east","easy","edge","else","even","ever",
  "evil","exit","face","fact","fade","fail","fair","fall","farm","fear","feel",
  "feet","fell","felt","file","fill","film","fire","firm","fish","five","flag",
  "flat","flow","folk","food","foot","form","fort","four","free","from","fuel",
  "full","fund","gain","gave","gear","gift","girl","give","glad","goal","goes",
  "gold","golf","gone","grew","grey","grow","gulf","hair","half","hall","hang",
  "hard","harm","hate","have","head","hear","heat","held","hell","here","hero",
  "high","hill","hire","hold","hole","holy","home","hope","host","hour","huge",
  "hung","hunt","hurt","idea","inch","into","iron","item","java","join","jump",
  "jury","just","keen","keep","kick","kill","kind","king","knew","know","lack",
  "lady","laid","lake","land","lane","lead","left","less","like","line","link",
  "list","live","load","loan","lock","logo","went","west","what","when","whom",
  "wide","wife","wild","will","wind","wine","wing","wire","wise","wish","with",
  "wood","wool","wore","work","yard","yeah","year","your","zero","zone","acre",
  "also","arch","atom","aunt","bark","bead","beak","beam","bean","beef","been",
  "beg","berm","bite","blab","blah","bled","bless","blob","blot","bong","boon",
  "boot","bore","bred","brow","buck","bulb","bulk","bull","bump","bunk","buoy",
  "burp","byte","cage","calf","cane","cape","cave","cert","chap","chef","chin",
  "chop","clam","clap","claw","clay","clef","clew","clip","clod","clog","clot",
  "club","clue","coal","coil","coke","cola","comet","cone","cook","cope","cord",
  "cork","corn","cot","coup","cozy","cram","craw","crew","crisp","croc","crow",
  "crud","cube","curb","curl","dais","dame","dare","darn","dart","dash","daze",
  "daze","dean","deck","deed","deem","deft","deli","dell","demo","dent","dire",
  "disc","diva","dive","dock","dole","doll","dome","dope","dorm","dote","dove",
  "doze","drab","drag","dram","drat","drew","drip","drool","drub","drum","dual",
  "duct","dull","dump","dune","dupe","dusk","earl","ease","echo","eden","edge",
  "edit","eel","eft","elan","elm","else","emit","etch","exam","fawn","faze",
  "feat","fend","fern","fete","feud","flab","flaw","flea","fled","flew","flex",
  "flip","flit","floe","flop","flow","foam","foci","fond","fore","fork","fowl",
  "fray","fret","frog","from","frost","froth","fume","funk","gale","gall","gape",
  "garb","gash","gasp","gate","gaze","gent","germ","gild","gilt","girl","gist",
  "glee","glen","glib","goad","goat","gore","gosh","gown","grab","gram","grape",
  "gust","hack","hale","hall","halo","hand","harm","harp","hash","haul","haunt",
  "haze","heap","heed","heel","herb","herd","hewn","hide","hike","hilt","hinge",
  "hint","hip","hive","hoax","hock","hoop","horn","hulk","hull","hump","hunk",
  "hymn","icon","idle","iglu","knit","knob","knot","lace","lame","lamp","lash",
  "laud","lawn","leaf","lean","leap","left","lend","levy","lint","lobe","loft",
  "loin","lore","lout","lure","lurk","lust","lute","lynx","mace","maid","mall",
  "malt","mane","mare","mash","mask","maze","mead","meal","mean","meat","memo",
  "mend","mesh","mire","mist","moan","moat","mode","mole","molt","monk","mood",
  "mope","moss","mote","mourn","muff","mule","muse","mutt","myth","nave","nerd",
  "nigh","nimble","nook","norm","nose","noun","nude","nuke","oafs","oaks","oats",
  "oath","ogle","ogre","omen","open","opus","oval","oven","pace","pact","page",
  "pail","pair","pale","palm","pane","pant","pare","park","pave","peak","peat",
  "peck","peer","pelt","perk","pest","phew","pike","pile","pill","pimp","pine",
  "pink","pipe","pirk","pith","plop","plot","plow","ploy","plum","plumb","plunge",
  "plunk","plus","poke","poll","polo","pond","pore","port","pose","posh","pour",
  "pout","prow","pull","pulp","pump","punk","pyre","quay","rack","raft","rage",
  "raid","rail","rain","rake","ramp","rang","rank","rant","rash","rasp","rave",
  "read","real","ream","reap","reef","reel","rein","rend","rent","reek","rest",
  "rice","rich","rife","rink","riot","ripe","rise","risk","rite","roan","roam",
  "roar","robe","rock","rode","romp","roof","rook","root","rope","rose","rote",
  "rout","rove","ruin","rule","rump","rung","rust","sage","sail","sake","sale",
  "same","sand","sane","sang","sash","save","scan","scar","seam","seep","self",
  "send","sewn","shed","shin","shop","shot","show","shun","shut","shy","sick",
  "silo","silt","sing","sire","skid","skim","skin","skip","skit","slag","slap",
  "slat","slaw","sled","slew","slim","slip","slog","slop","slot","slug","slum",
  "slur","smack","smear","smog","snag","snap","snare","snow","snub","snug","soap",
  "sock","sofa","song","soon","sore","sort","soul","span","spec","sped","spin",
  "spit","spot","spud","spur","stab","stag","star","stay","stem","step","stem",
  "stir","stop","stow","stub","stud","stun","suck","sulk","sung","sunk","sure",
  "surf","swab","swag","swam","swap","swat","sway","swum","tack","tame","tang",
  "tale","talk","tall","taut","teem","tend","term","text","thaw","then","they",
  "thin","this","thud","tick","tide","tilt","tome","tong","took","tool","toot",
  "tore","torn","toss","toil","tofu","tone","tort","tour","town","trek","trim",
  "trip","trod","true","truk","tuft","tune","turf","twin","typo","unit","upon",
  "vale","vane","vary","vast","veil","vein","vend","vent","verb","vest","veto",
  "vial","vice","view","vile","vine","visa","volt","wail","wait","wake","walk",
  "wall","wand","ward","ware","warm","warn","warp","wart","weal","wean","weep",
  "weld","welt","whim","whip","whit","whom","wilt","wimp","wink","wipe","wolf",
  "worm","writ","yarn","yore","yowl","zeal","zest","zinc","zing","zoom",
];

const english5: string[] = [
  "after","again","about","below","could","every","first","found","great","house",
  "large","learn","never","other","place","plant","point","right","small","sound",
  "spell","still","study","think","water","where","which","world","would","write",
  "happy","peace","black","board","brave","break","bring","build","built","carry",
  "catch","cause","chain","chair","chart","chase","cheap","check","chest","chief",
  "child","chose","civil","claim","class","clean","clear","clock","close","coach",
  "coast","color","count","court","cover","crash","crazy","cream","crime","cross",
  "crowd","crown","cycle","daily","dance","death","dozen","draft","drama","drawn",
  "dream","dress","drink","drive","dying","eager","early","earth","eight","elite",
  "empty","enemy","enjoy","enter","entry","equal","error","event","exact","exist",
  "extra","power","press","price","pride","prime","print","prior","prize","proof",
  "proud","prove","queen","quick","quiet","quite","radio","raise","range","rapid",
  "ratio","reach","ready","refer","rival","river","robot","rough","round","route",
  "royal","rural","scale","scene","scope","score","sense","serve","seven","shade",
  "shake","shall","shape","share","sharp","sheep","shelf","shell","shift","shirt",
  "shock","shoot","short","shown","sight","since","sixty","skill","sleep","slide",
  "smart","smile","smoke","solid","solve","sorry","south","space","spare","speak",
  "speed","spend","spent","split","spoke","sport","staff","stage","stake","stand",
  "youth","zeros","trend","tribe","trick","tried","troop","trout","truck","truly",
  "trump","trunk","trust","truth","tuner","twice","twirl","twist","tying","ultra",
  "uncle","under","unify","union","unite","until","upper","upset","usage","usual",
  "usher","utter","vague","valid","value","valve","vaunt","vault","venom","verse",
  "video","vigil","villa","vinyl","virus","visor","vista","vital","vivid","vocal",
  "voice","vouch","voila","vowel","voter","wafer","waist","waltz","wanna","waste",
  "watch","weird","whale","wheat","wheel","where","while","whirl","white","whole",
  "whose","width","wiped","witch","witty","woman","women","won't","words","worry",
  "worse","worst","worth","wrist","wrote","abide","abler","abort","abode","abyss",
  "acorn","acute","adept","admit","adopt","adore","adult","afoot","agile","agony",
  "agree","ahead","album","alert","alibi","alien","alike","align","alive","alley",
  "allow","allot","alone","along","aloft","amaze","amber","amend","among","ample",
  "angel","anger","angle","ankle","annex","antic","anvil","apply","apron","aptly",
  "ardor","arena","arise","array","arson","aside","asset","attic","audio","audit",
  "augur","avail","avert","avid","avoid","award","aware","awful","axial","babel",
  "basic","basis","batch","baton","beach","beady","began","begin","being","bench",
  "beset","bevel","bingo","birch","birth","bison","blame","bland","blank","blast",
  "blaze","bleak","bleat","bleed","blend","bless","blimp","blind","blink","bliss",
  "bloat","block","bloke","blood","bloom","blown","blunt","blurb","blurt","blush",
  "bogus","boney","bonus","booze","botch","bound","boxer","brash","bream","bride",
  "brief","brine","broil","brook","brood","broth","brown","brunt","brush","brute",
  "buddy","bugle","bulge","bunch","buoys","burst","bylaw","cadet","candy","canon",
  "carat","cargo","carol","carve","cavil","cedar","cease","chasm","chess","chief",
  "chimp","chord","cinch","clack","clamp","clank","clash","clasp","claw","cleft",
  "clerk","click","cliff","cling","clink","cloak","clone","cloud","cluck","clump",
  "cobra","comet","comic","comma","conch","condo","coral","couch","could","counl",
  "coupe","crave","crawl","creek","creep","crest","crimp","crisp","croak","crook",
  "croon","crumb","crush","crust","crypt","cubic","curly","curry","curse","cushy",
  "cyber","daddy","datum","daunt","debts","decay","decoy","decry","delay","delta",
  "delve","depot","derby","dowel","downs","dowry","drain","drape","drawl","drear",
  "drill","drove","dryer","dwarf","dwell","eagle","easel","edict","eight","elbow",
  "elder","elfin","elide","email","embed","emcee","eject","erupt","evade","evict",
  "evoke","exalt","exert","exile","exude","fable","facet","faith","false","fancy",
  "farce","fatal","fault","feast","fecal","feint","felon","fence","fetch","fewer",
  "feign","fiber","fiend","fight","filth","finch","flair","flame","flank","flare",
  "flash","flask","fleck","fleet","flesh","flick","fling","flint","flock","flood",
  "floor","flora","flour","flush","flute","flyby","foamy","focal","foray","forge",
  "forte","forum","foyer","frail","freak","fresh","friar","frill","frisk","front",
  "froth","froze","frugal","fully","fungi","funky","fussy","fuzzy","gaffe","gaily",
  "gaudy","gauge","geese","genre","giddy","girth","given","gizmo","gland","glare",
  "glass","glaze","gleam","glide","glint","gloom","gloss","glove","glyph","gnarly",
  "gorge","gouge","grace","grade","grail","grasp","grass","grate","graze","greed",
  "greet","grief","grill","gripe","groan","groin","groom","grope","grout","growl",
  "grunt","guile","guise","gulch","gully","gusto","gypsy","habit","haven","hedge",
  "heist","hence","hertz","hinge","hippo","hoard","holly","honey","honor","hopeful",
  "hound","humor","husky","hyena","hyper","icily","ideal","idiot","image","imply",
  "inbox","indie","inert","infix","ingot","input","inter","intro","inure","invert",
  "irate","irony","joust","knave","kneel","knife","knock","knoll","known","label",
  "lance","lanky","lapel","laser","latch","later","latte","laugh","lease","legal",
  "leash","lemon","level","libel","light","limit","linen","liner","lingo","liver",
  "llama","lobby","local","lodge","logic","loopy","lowly","lucid","lucky","lunar",
  "lusty","lyric","magic","major","maker","manor","maple","march","marsh","matte",
  "maxim","mayor","mealy","media","medic","mercy","merge","merit","meter","might",
  "mince","minor","minus","mirth","miser","mogul","moist","molar","money","month",
  "moral","moron","morph","mossy","motel","mourn","mouth","muddy","mulch","mummy",
  "murky","music","musty","naive","nasty","navel","nerve","night","ninja","nippy",
  "noble","noise","nomad","notch","novel","nymph","oasis","ocean","occur","octave",
  "offer","often","olive","onset","optic","orbit","order","organ","ought","ovary",
  "ovoid","oxide","ozone","parka","party","pasta","patch","patio","pause","payee",
  "peach","penal","perch","phase","phone","photo","piano","pilot","pinch","pixel",
  "pizza","plaid","plain","plane","plaza","plead","pleat","pluck","plumb","plump",
  "plunk","plush","poach","poety","polar","polka","poppy","porch","posed","posse",
  "potty","pouch","poult","pound","prank","prayer","prism","privy","prose","prowl",
  "prude","prune","psalm","pubic","purge","pushy","quack","qualm","query","queue",
  "quill","quirk","quota","quote","rabbi","rabid","radar","ranch","rangy","raspy",
  "rebel","recap","redux","regal","reign","relax","relic","remit","remix","renew",
  "repay","repel","rerun","reset","resin","reedy","rogue","roost","ruddy","ruler",
  "rusty","sadly","saint","salad","salon","sauce","scalp","scald","scalp","scam",
  "scant","scare","scary","scoff","scold","scoop","scorch","scorn","scout","scram",
  "screw","scrub","seize","shack","shady","shame","shark","shawl","sheen","sheer",
  "slain","slant","slash","slave","sleet","sleek","slick","slime","slimy","slope",
  "slosh","sloth","slung","slunk","slurp","smack","small","smash","smear","snack",
  "snail","snake","snare","snarl","sneak","snide","sniff","snore","snowy","snub",
  "soggy","spank","spark","spawn","spear","speck","spiel","spill","spine","spoil",
  "spook","spool","spoon","spore","spray","squad","squat","squid","stain","stale",
  "stalk","stall","stamp","stank","stark","stash","state","stave","steak","steal",
  "steam","steel","steep","steer","stern","stiff","sting","stint","stoic","stomp",
  "stout","stove","strap","stray","strep","strip","strut","stuck","style","suave",
  "sugar","sulky","sunny","super","surge","swamp","swear","sweat","sweep","sweet",
  "swept","swill","swine","swipe","swirl","swoop","synth","tabby","tacit","talon",
  "tango","tardy","taunt","teary","tepid","terse","their","there","thick","thing",
  "thorn","those","throb","throw","thump","thyme","tidal","timid","tipsy","tired",
  "titan","tonal","tonic","topaz","total","totem","toxic","trace","track","trail",
  "train","tramp","trash","trawl","triad","tweed","twerp","udder","ultra","uncut",
  "undue","unfit","urban","verge","vigor","vicar","video","vigil","villa","viper",
  "visit","visor","vixen","vizor","vogue","wacky","wader","walnut","watch","whack",
  "whelp","whiff","whiney","whoop","widen","wider","windy","wired","woken","wolfy",
  "wordy","wormy","wrath","wring","wrong","wrote","wryly","yeast","yield","young",
];

const english6: string[] = [
  "around","enough","coding","access","analog","anchor","backup","binary","bitmap",
  "buffer","bundle","button","bypass","client","column","cookie","cursor","device",
  "dialog","domain","driver","engine","entity","export","filter","folder","format",
  "global","header","import","insert","kernel","linker","logger","memory","method",
  "module","object","packet","parser","plugin","portal","prefix","prompt","python",
  "render","router","script","sector","server","socket","source","static","stream",
  "string","struct","syntax","system","tablet","thread","toggle","upload","vector",
  "widget","absorb","accent","accept","accrue","action","active","actual","affect",
  "afford","afraid","agency","agenda","agreed","albeit","alpine","always","amount",
  "anguish","answer","appear","armful","arouse","arrest","arrive","artful","assert",
  "assign","assist","assure","attach","attend","attire","august","awhile","banter",
  "barely","barren","battle","behold","beside","betray","beyond","blight","blotch",
  "blower","boiler","borrow","bounce","bother","bought","brazil","breeze","bright",
  "brooch","budget","burrow","butter","cactus","camera","candle","canopy","canter",
  "career","casket","castle","casual","caught","caution","center","change","chapel",
  "charge","chatty","chilly","choice","chrome","circle","clench","clever","clinch",
  "cloudy","clover","coerce","column","combat","commit","compel","comply","concur",
  "confer","cotton","counsel","couple","coupon","coyote","cradle","crafty","cranny",
  "create","credit","crutch","cupola","custom","dagger","danger","darken","debate",
  "decent","decide","defeat","defend","define","degree","demand","depend","desert",
  "design","detail","detect","devote","differ","direct","disarm","dollar","donate",
  "donkey","double","ductile","during","dwight","easily","eighty","either","emerge",
  "empire","employ","enable","encircle","endure","engage","ensure","equity","escape",
  "estate","esteem","evolve","excite","exempt","expand","expect","expose","extend",
  "fabric","failed","fairly","fallen","fallow","famine","fasten","father","fathom",
  "faucet","faulty","feisty","fidget","fierce","figure","flimsy","flinch","fluent",
  "fonder","forage","forbid","forest","formal","foster","fourth","frigid","frolic",
  "frozen","gadget","garlic","gentle","gather","gifted","glance","glossy","govern",
  "gravel","grieve","grovel","guitar","hamper","handle","happen","harbor","harken",
  "healer","helper","hinder","hollow","honest","hoopla","hostage","hunter","hustle",
  "impact","impose","incite","inform","insist","insure","intent","invest","invoke",
  "irenic","island","isolate","jargon","jester","jingle","jostle","jovial","jumble",
  "jungle","launch","lessen","lesson","letter","likely","listen","little","lively",
  "locate","longer","lowest","lumber","manage","manual","marble","marvel","mayhem",
  "meadow","middle","mighty","mirror","modern","modify","mother","motion","mortal",
  "napkin","narrow","nation","native","nearby","needle","nibble","noodle","normal",
  "notice","notify","nudge","number","obtain","offers","offset","online","oracle",
  "origin","outlaw","output","outsmart","packet","palace","pardon","parent","passes",
  "patent","payoff","people","permit","person","pillar","pirate","preach","prefer",
  "priest","prison","profit","prosper","puzzle","quartz","racket","random","really",
  "reason","recall","reform","region","relate","remain","remind","remote","repair",
  "repeat","report","resist","result","reveal","review","reward","ribbon","rustic",
  "safely","sample","savage","school","secret","simple","single","sister","sketch",
  "stable","stolen","strong","strove","studio","submit","suffer","summer","switch",
  "symbol","taught","theory","though","thread","throng","timber","traded","tunnel",
  "though","thirty","thrash","tickle","tingle","tongue","touchy","towels","travel",
  "tumble","tundra","turkey","turned","typing","umpire","united","unlock","unpack",
  "unruly","urgent","useful","vacuum","vanish","vanity","varied","varied","versus",
  "vessel","victim","virtue","vision","visual","vulture","wander","warmth","wasted",
  "waters","wealth","weekly","weight","winter","wonder","worthy","woundy","yearly",
  "yellow","zenith",
];

const english7: string[] = [
  "browser","computer","software","keyboard","website","digital","virtual","amazing",
  "explore","develop","creative","learning","because","between","brought","certain",
  "example","explain","message","picture","program","quality","receive","science",
  "someone","student","success","support","through","ability","absence","academy",
  "account","accused","achieve","acquire","address","advance","advised","against",
  "airline","airport","alcohol","already","analyst","ancient","another","anxiety",
  "applied","arrange","arrival","article","assault","assumed","attempt","attract",
  "average","balance","banking","barrier","battery","bedroom","believe","beneath",
  "benefit","billion","brother","burning","cabinet","capital","captain","capture",
  "careful","carrier","ceiling","central","century","chamber","channel","chapter",
  "charity","checked","chicken","circuit","citizen","clarity","classic","climate",
  "cluster","comfort","command","comment","company","compare","compete","complex",
  "concept","concern","conduct","confirm","connect","consist","contact","contain",
  "content","context","control","convert","correct","council","country","crystal",
  "culture","current","dealing","decided","decline","deliver","density","deposit",
  "desktop","despite","destroy","develop","devoted","summary","waiting","welfare",
  "without","witness","working","writing","written","ability","absence","academy",
  "abscond","absolve","abstain","absurd","abusive","acclaim","account","accuse",
  "achieve","acquire","acronym","address","advance","adverse","advisor","affable",
  "affairs","against","ageless","aggress","agitate","ailment","airflow","alcohol",
  "alright","altered","amassed","amazing","amplify","ancient","anymore","anxiety",
  "appease","appoint","approve","archive","armored","arrange","arrival","arsenal",
  "artisan","ascribe","asphalt","aspirin","assembly","astound","athlete","awesome",
  "awkward","backfire","balloon","banquet","bargain","barnacle","blossom","cabinet",
  "catalog","caution","chaotic","charity","clarify","clatter","cleanse","climate",
  "cluster","coastal","concede","condemn","condone","confine","confirm","confuse",
  "consent","contain","contest","contour","convict","copycat","cradles","crumble",
  "crusade","crystal","curator","decline","delight","deposit","descent","devoted",
  "digital","diagram","dismiss","display","distant","distort","disturb","diverse",
  "divided","dolphin","dominate","drought","dynasty","earnest","ecology","edition",
  "element","emotion","endorse","enforce","enhance","enlarge","enlight","ensnare",
  "environ","episode","exhibit","exploit","express","extract","faction","fallout",
  "fantasy","fashion","festive","finance","fiction","fixture","flavour","forgive",
  "fortune","forward","fragile","freedom","fresher","fullest","furnish","gallery",
  "gateway","general","genuine","glitter","glorify","glorified","goblin","gradual",
  "harvest","history","holiday","hopeful","hostile","however","ignite","imagery",
  "imagine","implode","impress","improve","incline","innocent","insight","inspire",
  "intense","involve","isolate","joyful","justice","kitchen","knowing","lasting",
  "layered","lecture","legible","lengthy","lessons","liberal","limited","logical",
  "looking","loyalty","maximum","meaning","meeting","mention","minimum","miracle",
  "mission","mixture","monster","morning","movement","mystery","natural","network",
  "nothing","nuclear","obvious","opinion","optimal","organic","outlook","outside",
  "package","passion","patient","pattern","penalty","pension","percent","perfect",
  "perhaps","persist","physics","pioneer","popular","portion","possess","posture",
  "poverty","present","private","process","promise","protect","protein","protest",
  "provide","publish","purpose","quantum","quickly","quietly","railway","rapidly",
  "recover","reflect","release","request","require","resolve","respond","restore",
  "revenue","reverse","revival","routine","savings","several","shelter","silence",
  "similar","skilled","slender","speaker","special","sponsor","stadium","station",
  "storage","strange","stretch","subject","sunrise","surface","survive","suspect",
  "usually","variety","venture","version","veteran","village","violent","visible",
  "volcano","watcher","weather","weekend","whether","whoever","willing","windows",
  "musical","mystery","neutral","obvious","offline","organic","partner","pattern",
  "pioneer","popular","portion","possess","private","process","protest","provide",
];

const english8: string[] = [
  "internet","network","database","function","variable","algorithm","framework",
  "absolute","abstract","accurate","activate","adequate","adjacent","adjusted",
  "admiring","adoption","advanced","advocacy","affinity","affluent","agreeable",
  "airplane","alliance","allocate","allowing","alphabet","although","ambiance",
  "ambition","amenable","amicable","amplified","analysis","annotate","appendix",
  "approach","approval","argument","aromatic","assembly","assessed","asteroid",
  "athletic","attached","attitude","audience","autonomy","backbone","backfire",
  "balanced","becoming","behavior","boldness","boundary","browsing","building",
  "capacity","cardinal","causally","cellular","chemical","classify","climatic",
  "coherent","collapse","colonial","colorful","commence","commerce","compiler",
  "complete","composed","compress","comprise","conceive","conclude","concrete",
  "conflict","congress","consider","constant","contract","contrary","convince",
  "critical","crossover","cultural","database","daylight","deadline","decisive",
  "decrease","delegate","delicate","depicted","describe","detailed","diagnose",
  "directed","discover","distinct","domestic","dominant","duration","dynamics",
  "educated","election","emerging","employed","empower","encoding","energize",
  "engineer","enormous","epidemic","establish","evaluate","evolving","examine",
  "exchange","exercise","explicit","exposure","exterior","familiar","featured",
  "feedback","festival","fighting","filtered","financial","flexible","flooding",
  "focusing","footprint","forecast","fracture","frontier","generate","generous",
  "globally","graduate","guidance","handling","harmless","headache","heritage",
  "hospital","humanity","identity","imagined","immunity","improved","incident",
  "included","incoming","industry","informed","initiate","innovate","insights",
  "integral","interact","interest","interior","interval","involved","isolated",
  "keyboard","landmark","language","launched","learning","lifetime","likewise",
  "locality","maintain","managing","material","measured","medicine","moderate",
  "momentum","monetary","movement","multiple","national","negative","oriented",
  "overcome","overview","paradise","parallel","peaceful","peaceful","perceive",
  "platform","positive","powerful","practice","priority","probable","produced",
  "profound","property","proposed","prospect","publicly","purchase","quantity",
  "question","rational","reaction","readable","realized","recovery","register",
  "relevant","reliable","remember","research","resident","resource","response",
  "schedule","security","selected","sensible","sequence","snapshot","solution",
  "standard","strategy","strength","strongly","structure","suitable","template",
  "thousand","together","tomorrow","transfer","universe","validate","valuable",
  "vertical","violence","volcanic","warranty","whatever","whenever","wherever",
  "wholesome","wonders","yourself",
];

const english9: string[] = [
  "algorithm","framework","ambiguous","anonymous","benchmark","calculate",
  "candidate","challenge","cognition","community","competent","component",
  "composite","construct","consuming","container","continues","cooperate",
  "customize","dangerous","datapoint","dedicated","different","dimension",
  "discovery","diversity","efficient","elaborate","eliminate","embedding",
  "emergency","emphasize","encounter","encourage","endurance","establish",
  "expansion","expertise","explosive","extensive","financial","formulate",
  "frequency","gradually","guideline","highlight","important","impromptu",
  "incentive","inclusive","indicator","inference","influence","informant",
  "injection","integrity","interface","inventory","invisible","iteration",
  "knowledge","landscape","mechanism","memorable","milestone","narrative",
  "necessary","negotiate","objective","observant","offensive","operation",
  "organized","overpower","parameter","partition","permanent","precisely",
  "privilege","procedure","projected","propagate","prototype","qualified",
  "quarterly","realistic","recognize","recommend","redundant","reference",
  "reproduce","resilient","retention","retrieval","sacrifice","satisfied",
  "scholarly","sensitive","signature","situation","solutions","somewhere",
  "speculate","stimulate","strategic","structure","submarine","summarize",
  "syndicate","technique","temporary","testament","threshold","tolerance",
  "tradition","transform","translate","transport","treatment","unanimous",
  "uncertain","universal","unlimited","variables","variation","volunteer",
  "worldwide","yesterday","adventure","alignment","allowance","ambitious",
  "animation","authentic","awareness","blueprint","cognitive","columnist",
  "condition","connected","constrain","countless","credible","criterion",
  "curiosity","customize","dedicated","determine","deviation","dimension",
  "disruptive","effective","emotional","encrypted","endlessly","essential",
  "evolution","exclusive","exploding","extensive","faithfully","formative",
  "framework","guarantee","hardening","happiness","hierarchy","highlight",
  "impactful","implement","incentive","inclusive","indicator","influence",
  "integrate","invention","landscape","manageable","mentoring","milestone",
  "moderator","momentum","objective","organized","parameter","persistent",
  "potential","procedure","prototype","qualified","quarterly","reasoning",
  "recognize","resilient","retaining","rewarding","sacrifice","sensitive",
  "signature","stimulate","strategic","substance","surprised","trademark",
  "transform","translate","unanimous","universal","unlimited","variables",
  "variation","volunteer","worldwide","adventure","alignment","allowance",
];

// ─── Turkish ──────────────────────────────────────────────────────────────────

const turkish3: string[] = [
  "bir","çok","göz","yol","son","gün","bak","iki","ben","sen","git","gel","yer",
  "sev","ara","bul","yap","sor","ver","dün","acı","adı","ana","art","aşk","bal",
  "baş","bay","bez","biz","boş","buz","cam","can","cep","çay","çek","dağ","dal",
  "dam","dil","diş","duş","düz","ebe","erk","far","fal","fes","göl","güç","güz",
  "hal","ham","has","hat","hep","her","his","hoş","hız","iyi","ile","ilk","iri",
  "kel","kız","kim","kir","köy","kum","kuş","kül","laf","mal","maç","mum","net",
  "not","oda","oku","onu","oto","ova","öne","öte","pas","pek","pul","raf","rol",
  "sağ","sal","sat","sel","ses","sık","sır","sol","son","süt","şah","şal","şey",
  "taç","tam","tas","taş","tel","ten","tez","top","toz","tüm","tür","tüy","var",
  "vay","vur","yağ","yak","yan","yaş","yel","yen","yok","yön","yüz","zam","zar",
  "zil","zor","ağ","aş","at","av","ay","az","bağ","baş","boş","dua","ey","ev",
  "gaz","gel","gez","han","hay","hem","iç","iş","it","kör","kök","kür","od",
  "ön","öz","söz","su","şu","tal","um","ut","yat","yüz",
];

const turkish4: string[] = [
  "daha","hava","gece","ayak","anne","baba","kedi","masa","kapı","ayna","boya",
  "kova","toka","okul","renk","adam","adım","ağır","aile","akıl","aksi","alan",
  "alma","altı","amca","anma","araç","arka","artı","arzu","asal","asıl","asır",
  "atak","ateş","avlu","ayva","azim","azot","bant","batı","bavul","bayır","bebek",
  "beden","bela","belge","belki","belli","beyin","beyaz","bilgi","bilet","bilim",
  "bina","birim","bitki","bomba","borç","boyun","boyut","bölge","bölüm","börek",
  "budak","burun","butik","bütün","büyük","cami","canlı","ceket","cesur","cevap",
  "ceza","coşku","çaba","çadır","çanta","çare","çatal","çatı","çelik","çeşit",
  "çevre","çiçek","çizgi","çocuk","çözüm","daire","damat","damla","darbe","dava",
  "davul","dergi","devam","dolar","duman","duvar","dünya","edep","ekin","emir",
  "emek","enaz","epey","erken","esir","eşik","etki","evcil","fakir","fark","fark",
  "fate","fikir","fırın","fiyat","gelin","genç","geri","gezi","gibi","güçlü","güle",
  "gülüş","günah","güzel","haber","hafif","hain","hala","halk","hamur","hamle",
  "harç","hata","hayır","hazır","hediye","heves","hız","hizmet","horon","horoz",
  "hürmet","için","inanç","iplik","isim","istek","itiş","işte","izin","jokey",
  "kadın","kalp","kalın","kanca","kanunsuz","katı","kavim","kayış","kazan","kaçak",
  "kemer","kenar","kenti","kesik","kıble","kısa","kilim","klima","kolay","konak",
  "kural","kurşun","kuzey","künye","leke","liman","maden","makam","manca","marka",
  "merak","mesaj","meşe","mezar","midye","miras","misafir","model","müzik","nabız",
  "neden","nimet","niyeti","öfke","öğle","önem","öteki","özel","özgür","özlem",
  "saçı","sakin","sandal","sarıl","sayfa","seker","şeker","sepet","sergi","seyir",
  "sıkı","sınır","silah","siyah","sofra","soğan","sonuç","sorun","suç","sular",
  "tabak","tahıl","taraf","taşıt","tatil","tavan","temel","tepki","teras","tokat",
  "toplu","torun","turan","türkü","uçuş","ulusal","uygun","uzman","yaban","yabancı",
  "yakın","yalan","yanak","yapım","yargı","yavaş","yetki","yılan","yoğurt","yön",
  "yumuşak","yüklü","zaman","zemin","zinde",
];

const turkish5: string[] = [
  "bugün","yarın","sonra","önce","beyaz","siyah","elma","armut","kaşık","kenar",
  "fırın","tarih","müzik","yaprak","toprak","tohum","lamba","ışık","açlık","adres",
  "ahşap","akran","alarm","albüm","alçak","alıcı","alkış","altın","ambar","amber",
  "ampul","anket","anlam","antik","araba","arama","arazi","arena","arıza","arşiv",
  "asker","aşçı","aşırı","atlas","avize","ayran","bahis","bakır","balkan","banyo",
  "baraj","bayat","bedel","benzin","berber","besin","beste","bıçak","biber","bıyık",
  "bilim","binek","birey","birlik","bitki","boğaz","bomba","borsa","bozkır","bronz",
  "bucak","budak","buğday","buluş","büyük","canan","cazibe","ceket","cennet",
  "cephe","cesur","cevap","ceviz","ceylan","ciğer","cimri","cömert","çabuk","çağrı",
  "çakal","çalgı","çanak","çardak","çatış","çekim","çelik","çember","çeper","çığır",
  "çıkar","çiğdem","çizim","çoğul","çorap","çöküş","damar","danış","demet","deniz",
  "derya","devir","diken","divan","doğru","dolap","doğum","dorak","düşman","ebru",
  "edebî","efkar","ekran","eleman","enerji","engin","erkek","erişim","evren","fabrika",
  "fakül","final","gazete","genlik","gerçek","giysi","grevi","güçlük","gülüm","günay",
  "hafıza","haiku","hakem","halis","hamam","harita","hatay","heyel","hızlı","huzur",
  "içeriği","ihraç","ilâç","ilahi","ileti","imkân","inanış","isyan","izole","kadro",
  "kafile","kahve","kamp","kanat","kapak","kapan","karar","kaygı","kazma","kıdem",
  "kıtlık","kibir","kilise","kinom","kitap","kısmi","kolaj","koltuk","kombi","komur",
  "kopya","kozmos","köpük","küçük","lâyık","liman","lisans","lokal","lüzum","macera",
  "makine","masal","mayıs","meşru","metod","meyve","mezun","mızrak","misyon","miting",
  "moral","mutlu","nazik","neşeli","nihai","nihil","noter","nüfus","ocak","odası",
  "ofset","onay","organ","orman","panel","parça","pasta","patron","payda","pazar",
  "peşin","pilot","prens","proje","radar","rahat","rallye","rapor","reçel","refah",
  "rende","resmi","ritim","robot","roman","sahne","sakal","sanki","seçim","sefer",
  "senet","sezon","sıkıntı","sigorta","sipariş","siyasi","sohbet","soket","sorgu",
  "sorun","söylem","stres","tabii","talep","tamam","taraf","tarih","tasarı","teçhizat",
  "teknik","telif","temenni","tiraj","tokat","toplayıcı","torba","tuzak","uçak",
  "ulusal","uzunluk","verim","vidanjör","vize","yaklaşım","yatırım","yıkım","yorum",
  "yüksek","zafer","zengin","zirve",
];

const turkish6: string[] = [
  "ekran","klavye","yazılım","uygulama","bellek","tarayıcı","işlemci","dijital",
  "sanal","dosya","klasör","şifre","hesap","adres","android","animasyon","arayüz",
  "arşivleme","ayarlar","bilgisayar","bulut","derleyici","donanım","etiket","forum",
  "gezgin","grafik","güncelleme","güvenlik","hesaplama","iletişim","imleç","izleme",
  "karakter","kayıt","kısayol","kodlama","masaüstü","metin","modem","motor","oturum",
  "paket","parola","paylaşım","program","sekme","sertifika","simge","slayt","sürücü",
  "sürüm","tıklama","tuş","vektör","virüs","yama","yedekleme","yönlendirici","abartı",
  "abone","acayip","acemi","acente","adalet","aktarım","akıllı","akşam","alansal",
  "alışverişi","almanca","altyapı","ambalaj","analiz","anlatım","antrenman","anüler",
  "aplike","arabacı","aramak","arıtma","artık","atmak","ayrıntı","balkon","bankalık",
  "başarılı","batarya","bayrak","belirtmek","bencillik","benzeri","beraberlik","bevkiye",
  "bilgi","bitirim","boşver","buluşma","bütçesi","çamaşır","çalışma","çekimser",
  "çözücü","danışma","dayanışma","değişim","dekoru","deprem","devlet","doküman",
  "düzenli","ekonomi","eğitim","ekipman","emekli","endüstri","eskiden","evrensel",
  "faaliyet","fedakâr","firma","fiziksel","gelenek","getiriş","geçmiş","girişim",
  "görünüm","güçlendirme","güvenilir","harcama","hastalık","hayatta","idareci",
  "ilerleme","ilginç","ihtiyaç","imalat","imtihan","inanılmaz","insanlık","iradelik",
  "kalıntı","kapasite","karar verme","kayıplar","kişisel","komşuluk","kontrol",
  "koruma","kültürel","kuralcı","liderlik","memnuniyet","metodoloji","milli",
  "müdahale","müzisyen","nitelik","öncelik","örgütsel","özellik","pazarlama",
  "planlama","politika","pratik","refah","rekabet","reklam","sabahleyin","sağlıklı",
  "saldırganlık","sanayici","saygınlık","seçenek","serbestlik","siyaset","sistematik",
  "sorumluluk","standart","strateji","süreçler","şirket","taktiksel","tatminkâr",
  "teknik","üretim","verimlilik","vizyoner","yetkinlik","yönetim","ürünler",
];

const turkish7: string[] = [
  "telefon","kütüphane","hastane","öğrenci","öğretmen","arkadaş","kelebek","balina",
  "yunus","güneş","gezegen","başarı","mutluluk","sağlık","yaşam","abonelik",
  "açıklama","açılış","adalet","adaletli","aday","adımlama","adlandırma",
  "afişleme","ağırlamak","ağırlık","ağlamak","ahlaki","ailedeki","akılcı",
  "akıllıca","akılsız","aklama","akmakta","akraba","aktarma","aktüel","algoritma",
  "alacaklı","alakalı","alakasız","alaturka","alaycı","albeni","albino","aldatma",
  "algılama","alımlar","alındı","alıntı","alışkanlık","almanca","altyapı",
  "ambalaj","anadolu","analist","analiz","anlaşma","anlatan","anlatım","anormallik",
  "ansızın","antika","antikacı","antrakt","antrenman","aparatçı","apartman",
  "apolitik","arabacı","aramak","arıtma","artık","atmak","aydınlanma","ayrıntı",
  "azimli","bağımsız","bağlantı","bahçevan","bakanlar","bakışlar","balıkçı",
  "barınak","başarılar","başlangıç","batarya","bayramlar","belediye","bilgileri",
  "bilincini","bilinçli","bilişim","binlerce","boyutsal","bürokratik","bürokrasi",
  "çalışanlar","çevrimiçi","çoğunluk","çözümler","değerleri","değişimler",
  "demokratik","deneyimler","dönüşüm","düşünceli","eğitimsiz","ekonomide",
  "ekolojik","elektrikli","emekçiler","etkileyici","farkındalık","gelişmiş",
  "gelişmekte","gereksinim","girişimci","görevliler","güçlendirmek","güvenilirlik",
  "hizmetleri","ilişkileri","ilköğretim","iletişimci","insancıllık","istatistik",
  "kalkınmacı","kapsamlıyı","katılımcı","kişilikler","kültürellik","kurumsal",
  "liderlikçi","memnuniyetle","meslekçilik","milliyetçi","motivasyon","müzisyenler",
  "nitelendirmek","olduğunda","organizasyonu","öncelikli","örgütlülük","özgürlükçü",
  "planlayıcı","politikacı","profesyonel","sahiplenme","sanatçılık","sanayileşme",
  "sorunlarını","sosyolojik","stratejiler","sürdürülebilir","tasarımcı",
  "teknolojik","toplumsal","topluluklar","uluslararası","verimlilik","yenilikçilik",
  "yöneticiler","yönetişim","tarihçilik","bilinçdışı",
];

const turkish8: string[] = [
  "bilgisayar","internet","kütüphane","hastaneler","öğrenciler","öğretmenler",
  "arkadaşlar","kelebekler","gezegenleri","başarılarımız","mutluluklarımız",
  "sağlıklarımız","birlikte","anlayış","çözümleme","anlayışlı","teknoloji",
  "bürokrasi","demokrasi","katılımcı","düzenleme","ekosistem","finansman",
  "güvensizlik","hastalıklar","iletişimde","yatırımlar","kalkınmaya","gelişimde",
  "mütevazılık","özgürlükler","planlamalar","toplumların","uluslararası",
  "verimlilik","yeteneklilik","yöneticileri","kuruluşları","uygulamalar",
  "süreçlerin","standartlar","projeler","anlaşmalar","politikalar","ekonomiler",
  "kalkınmalar","reformları","sorumluluğu","stratejiler","teknikler","üretkenlik",
  "işbirliği","faaliyetleri","düşünceleri","değerlerin","kapasiteler","kurumsallık",
  "güçlendirme","müdahaleler","sistemlerin","şeffaflık","hesap verebilirlik",
  "sürdürülebilir","bütünleşik","performans","yükümlülük","taahhütler","karar alma",
  "yenilikçilik","entegrasyon","koordinasyon","konsolidasyon","decentralizasyon",
  "demokratikleşme","küreselleşme","modernleşme","liberalleşme","dijitalleşme",
  "sanayileşme","kentleşme","bürokratikleşme","standardizasyon","optimizasyon",
];

const turkish9: string[] = [
  "uluslararası","teknoloji","demokratik","kalkınmacı","kapitalizm","sosyalizm",
  "federalizm","laikleşme","özgürleşme","çoğulculuk","ekonomide","bölgesellik",
  "sosyoloji","psikoloji","antropoloji","arkeoloji","metodoloji","teknolojik",
  "biyolojik","jeolojik","astroloji","mitoloji","terminoloji","epidemioloji",
  "profesyonel","kurumsal","akademik","stratejik","sistematik","demokratik",
  "pragmatik","analitik","yaratıcılık","üretkenlik","sürdürülebilirlik",
  "hesap verebilirlik","performans değerlendirme","koordinasyon","entegrasyon",
  "organizasyon","katılımcılık","yönetişim","ademi merkezileşme","yerelleşme",
  "özerkleşme","modernizasyon","standarizasyon","liberalizasyon","özelleştirme",
  "kamulaştırma","demokratikleşme","küreselleşme","yeşillendirme","sürdürülebilir",
  "güçlendirme","bilinçlendirme","farkındalık","vatandaşlık","cumhuriyet","anayasal",
  "yargısal","yasama","yürütme","yargı","egemenlik","özgürlük","eşitlik","adalet",
  "dayanışma","toplumsal","ekonomik","kültürel","siyasal","tarihsel","coğrafi",
];

// ─── Merged export ────────────────────────────────────────────────────────────

export const wordBanks: Record<Language, string[]> = {
  english: [
    ...english3,
    ...english4,
    ...english5,
    ...english6,
    ...english7,
    ...english8,
    ...english9,
  ],
  türkçe: [
    ...turkish3,
    ...turkish4,
    ...turkish5,
    ...turkish6,
    ...turkish7,
    ...turkish8,
    ...turkish9,
  ],
};

// Per-length lookup maps (built once at module load)
const buildLengthMap = (words: string[]): Map<number, string[]> => {
  const map = new Map<number, string[]>();
  for (const w of words) {
    const len = w.length;
    if (!map.has(len)) map.set(len, []);
    map.get(len)!.push(w);
  }
  return map;
};

const englishByLength = buildLengthMap(wordBanks.english);
const turkishByLength = buildLengthMap(wordBanks.türkçe);

const byLength: Record<Language, Map<number, string[]>> = {
  english: englishByLength,
  türkçe: turkishByLength,
};

// ─── Helper functions ─────────────────────────────────────────────────────────

export const getRandomWord = (lang: Language): string => {
  const words = wordBanks[lang];
  return words[Math.floor(Math.random() * words.length)];
};

export const getWordOfLength = (lang: Language, length: number): string => {
  const map = byLength[lang];
  if (map.has(length)) {
    const arr = map.get(length)!;
    return arr[Math.floor(Math.random() * arr.length)];
  }
  // Find nearest available length
  const lengths = [...map.keys()];
  lengths.sort((a, b) => Math.abs(a - length) - Math.abs(b - length));
  const nearest = map.get(lengths[0])!;
  return nearest[Math.floor(Math.random() * nearest.length)];
};

export const getWordInRange = (lang: Language, min: number, max: number): string => {
  const words = wordBanks[lang].filter(w => w.length >= min && w.length <= max);
  if (words.length === 0) return getRandomWord(lang);
  return words[Math.floor(Math.random() * words.length)];
};

export const getLetterCountForLevel = (level: number): number => Math.min(level + 2, 9);
